update influx data directory
eu-nebulous/helm-charts pull request #36
Opened 2024-11-26 14:24 UTC by jmarchel7bulls

2024-11-26 14:24 UTC, jmarchel7bulls commented
https://github.com/eu-nebulous/influxdb/issues/5

2024-11-26 14:34 UTC, yoctozepto commented
I don't see how this addresses that issue. Is the data somehow in that `...2` directory instead of the default one?

2024-11-26 14:35 UTC, yoctozepto requested changes
Please clarify the change.

2024-12-03 14:43 UTC, yoctozepto approved these changes

2024-12-03 14:52 UTC, merged